use anyhow::{Context, Result};
use camino::{Utf8Path, Utf8PathBuf};
use serde::Serialize;
use walkdir::WalkDir;

use crate::config::PacketProfile;

#[derive(Debug, Serialize)]
struct PacketOutcome {
    packet: String,
    status: String,
    notes: String,
}

pub fn run(source: &Utf8Path, target: &Utf8Path) -> Result<()> {
    let root = target.join(".c-to-rust-port");
    std::fs::create_dir_all(root.join("units/000-source-map"))?;
    std::fs::create_dir_all(root.join("prompt_profiles"))?;
    let profile = PacketProfile::default();
    profile.write_to(&root.join("prompt_profiles/translator-default.toml"))?;
    write_packet(source, target, &root.join("units/000-source-map/TASK.md"))?;
    let outcome = PacketOutcome {
        packet: "000-source-map".to_string(),
        status: "planned".to_string(),
        notes: "generated by c2rust-port v1".to_string(),
    };
    std::fs::write(
        root.join("packet_outcomes.jsonl"),
        format!("{}\n", serde_json::to_string(&outcome)?),
    )?;
    println!("wrote packet plan under {root}");
    Ok(())
}

fn write_packet(source: &Utf8Path, target: &Utf8Path, path: &Utf8Path) -> Result<()> {
    let files = first_source_files(source, 8)?;
    let mut text = String::new();
    text.push_str("# TASK: Source Map Bootstrap\n\n");
    text.push_str("## Scope\n");
    text.push_str("Draft a narrow Rust porting plan for the listed source slice only. Preserve the process and data-flow boundaries from the generated repo map.\n\n");
    text.push_str("## Required Context\n");
    text.push_str(
        "- Read `.c-to-rust-port/SOURCE_REPO_MAP.md` for source process flow and data flow.\n",
    );
    text.push_str(
        "- Read `.c-to-rust-port/RUST_MIRROR_PLAN.md` for the initial Rust module layout.\n",
    );
    text.push_str("- Do not invent a different module structure unless the map evidence is wrong and you document why.\n\n");
    text.push_str("## Source Slice\n");
    for file in &files {
        text.push_str(&format!("- `{file}`\n"));
    }
    text.push_str("\n## Target Rust Files\n");
    text.push_str(&format!("- `{}`\n", target.join("src/lib.rs")));
    text.push_str("- Add files only if the apply/converge packet explicitly allows it.\n\n");
    text.push_str("## Expected Behavior\n");
    text.push_str("Preserve observable behavior from the source slice. If behavior is unclear, write questions and evidence instead of guessing.\n\n");
    text.push_str("## Translator Restrictions\n");
    text.push_str("- Do not run git.\n");
    text.push_str("- Do not run Cargo, builds, benchmarks, package managers, or broad scans.\n");
    text.push_str("- Do not edit the shared worktree.\n");
    text.push_str("- Produce a draft patch and notes only.\n\n");
    text.push_str("## Allowed Verification Command\n");
    text.push_str("None for translator packets. Apply/converge packets own verification.\n");
    std::fs::write(path, text).with_context(|| format!("write {path}"))
}

fn first_source_files(source: &Utf8Path, limit: usize) -> Result<Vec<Utf8PathBuf>> {
    let mut files = Vec::new();
    for entry in WalkDir::new(source).into_iter().filter_map(Result::ok) {
        if !entry.file_type().is_file() {
            continue;
        }
        let path = Utf8PathBuf::from_path_buf(entry.path().to_path_buf())
            .map_err(|p| anyhow::anyhow!("non-utf8 path: {}", p.display()))?;
        if matches!(
            path.extension(),
            Some("c" | "cc" | "cpp" | "cxx" | "h" | "hpp")
        ) {
            files.push(path.strip_prefix(source).unwrap_or(&path).to_path_buf());
        }
        if files.len() >= limit {
            break;
        }
    }
    Ok(files)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn packet_profile_round_trips() {
        let dir = camino::Utf8PathBuf::from_path_buf(
            std::env::temp_dir().join(format!("c2rust-port-profile-test-{}", std::process::id())),
        )
        .unwrap();
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("profile.toml");
        let profile = PacketProfile::default();
        profile.write_to(&path).unwrap();
        assert_eq!(PacketProfile::read_from(&path).unwrap(), profile);
        let _ = std::fs::remove_file(path);
        let _ = std::fs::remove_dir(dir);
    }
}
