use anyhow::{Context, Result};
use camino::{Utf8Path, Utf8PathBuf};
use rusqlite::{Connection, params};
use serde::Serialize;
use std::collections::BTreeSet;
use walkdir::WalkDir;

use crate::config::PacketProfile;

#[derive(Debug, Serialize)]
struct PacketOutcome {
    packet: String,
    status: String,
    notes: String,
}

#[derive(Debug, Serialize)]
struct CitationValidationReport {
    status: String,
    rows: Vec<CitationValidationRow>,
}

#[derive(Debug, Serialize)]
struct CitationValidationRow {
    citation: String,
    status: String,
    detail: String,
}

#[derive(Debug, Default)]
struct PacketSlice {
    feature: String,
    files: Vec<Utf8PathBuf>,
    citations: Vec<String>,
    blockers: Vec<String>,
}

pub fn run(source: &Utf8Path, target: &Utf8Path) -> Result<()> {
    let root = target.join(".c-to-rust-port");
    std::fs::create_dir_all(root.join("units/000-source-map"))?;
    std::fs::create_dir_all(root.join("prompt_profiles"))?;
    std::fs::create_dir_all(root.join("agents"))?;
    std::fs::create_dir_all(root.join("codex_runs"))?;
    let profile = PacketProfile::default();
    profile.write_to(&root.join("prompt_profiles/translator-default.toml"))?;
    copy_evidence_queries(source, &root)?;
    let slice = select_packet_slice(source, 8)?;
    let validation = validate_seed_citations(source, &slice.citations)?;
    write_citation_validation(&root, &validation)?;
    ensure_citation_validation_passed(&validation)?;
    write_packet(
        source,
        target,
        &root.join("units/000-source-map/TASK.md"),
        &slice,
    )?;
    write_codex_agent_docs(&root.join("agents"))?;
    write_codex_review_checklist(&root.join("agents/REVIEW_CHECKLIST.md"))?;
    write_codex_runbook(&root.join("agents/RUNBOOK.md"), &profile)?;
    let outcome = PacketOutcome {
        packet: "000-source-map".to_string(),
        status: "planned".to_string(),
        notes: "generated by c2rust-port v1".to_string(),
    };
    std::fs::write(
        root.join("packet_outcomes.jsonl"),
        format!("{}\n", serde_json::to_string(&outcome)?),
    )?;
    println!("wrote packet plan under {root}");
    Ok(())
}

fn write_packet(
    source: &Utf8Path,
    target: &Utf8Path,
    path: &Utf8Path,
    slice: &PacketSlice,
) -> Result<()> {
    let mut text = String::new();
    text.push_str("# TASK: Source Map Bootstrap\n\n");
    text.push_str("## Scope\n");
    text.push_str(&format!(
        "Draft a narrow Rust porting plan for the `{}` source slice only. Preserve the process and data-flow boundaries from the generated repo map.\n\n",
        slice.feature
    ));
    text.push_str("## Required Context\n");
    text.push_str(
        "- Read `.c-to-rust-port/SOURCE_REPO_MAP.md` for source process flow and data flow.\n",
    );
    text.push_str(
        "- Read `.c-to-rust-port/RUST_MIRROR_PLAN.md` for the initial Rust module layout.\n",
    );
    text.push_str(&format!(
        "- Query source knowledge at `{}/.c2rust-port/knowledge/evidence.db` before proposing code.\n",
        source
    ));
    text.push_str(&format!(
        "- Use source fact rows from `{}/.c2rust-port/knowledge/facts/*.jsonl` for citations.\n",
        source
    ));
    text.push_str(
        "- Read `.c-to-rust-port/EVIDENCE_QUERIES.md` for SQL recipes against `evidence.db`.\n",
    );
    text.push_str(
        "- Read `.c-to-rust-port/CITATION_VALIDATION.md` for generated seed-citation validation.\n",
    );
    text.push_str("- Do not invent a different module structure unless the map evidence is wrong and you document why.\n\n");
    if !slice.blockers.is_empty() {
        text.push_str("## Source Map Blockers\n");
        text.push_str("Source map incomplete for this packet until these deep-analysis blockers are addressed or explicitly judged irrelevant:\n");
        for blocker in &slice.blockers {
            text.push_str(&format!("- {blocker}\n"));
        }
        text.push('\n');
    }
    text.push_str("## Required Source Evidence\n");
    text.push_str("- Cite at least three source fact rows before the unified diff.\n");
    text.push_str("- Use citation format `facts/<table>.jsonl:<key>` or `evidence.db:<table>:<primary-key>`.\n");
    text.push_str("- At least one citation must come from `symbols`, `call_edges`, `dataflow_edges`, `feature_tags`, or `equivalence_edges`.\n");
    text.push_str("- If citations are unavailable, return a blocker instead of a patch.\n\n");
    if !slice.citations.is_empty() {
        text.push_str("## Seed Citations\n");
        for citation in &slice.citations {
            text.push_str(&format!("- `{citation}`\n"));
        }
        text.push('\n');
    }
    text.push_str("## Source Slice\n");
    for file in &slice.files {
        text.push_str(&format!("- `{file}`\n"));
    }
    text.push_str("\n## Target Rust Files\n");
    text.push_str(&format!("- `{}`\n", target.join("src/lib.rs")));
    text.push_str("- Add files only if the apply/converge packet explicitly allows it.\n\n");
    text.push_str("## Expected Behavior\n");
    text.push_str("Preserve observable behavior from the source slice. If behavior is unclear, write questions and evidence instead of guessing.\n\n");
    text.push_str("## Translator Restrictions\n");
    text.push_str("- Do not run git.\n");
    text.push_str("- Do not run Cargo, builds, benchmarks, package managers, or broad scans.\n");
    text.push_str("- Do not edit the shared worktree.\n");
    text.push_str("- Produce a draft patch and notes only.\n");
    text.push_str("- Use only the context in this packet and the named target file excerpts.\n");
    text.push_str("- Every behavior claim must be backed by a source fact citation.\n");
    text.push_str("- If context is insufficient, return the smallest useful skeleton and list the missing excerpts.\n\n");
    text.push_str("## Patch Contract\n");
    text.push_str(
        "- Output `Source Evidence`, then one unified diff, then an `Assumptions` section.\n",
    );
    text.push_str("- Do not mark an existing file as `new file mode`.\n");
    text.push_str(
        "- Do not add modules unless the target file list explicitly names the module file.\n",
    );
    text.push_str(
        "- Do not remove existing public items unless the task explicitly asks for removal.\n",
    );
    text.push_str("- Do not use crates that are not already in `Cargo.toml`.\n");
    text.push_str(
        "- Preserve source enum order, integer discriminants, and public naming evidence.\n",
    );
    text.push_str(
        "- Prefer allocation-free constants/slices over maps unless keyed lookup is required.\n\n",
    );
    text.push_str("## Allowed Verification Command\n");
    text.push_str("None for translator packets. Apply/converge packets own verification.\n");
    std::fs::write(path, text).with_context(|| format!("write {path}"))
}

fn write_codex_agent_docs(dir: &Utf8Path) -> Result<()> {
    write_translator_agent(&dir.join("01-translator.md"))?;
    write_source_fidelity_reviewer(&dir.join("02-source-fidelity-reviewer.md"))?;
    write_rust_reviewer(&dir.join("03-rust-reviewer.md"))?;
    write_apply_converge_agent(&dir.join("04-apply-converge.md"))?;
    Ok(())
}

fn write_translator_agent(path: &Utf8Path) -> Result<()> {
    let mut text = String::new();
    text.push_str("# Codex Translator Agent\n\n");
    text.push_str("Draft narrow Rust translations from one packet. This role is intentionally no-build and no-mutation.\n\n");
    text.push_str("## Hard Rules\n\n");
    text.push_str("- Do not run commands.\n");
    text.push_str("- Do not use git.\n");
    text.push_str(
        "- Do not run Cargo, builds, tests, benchmarks, package managers, or broad scans.\n",
    );
    text.push_str("- Do not claim verification.\n");
    text.push_str("- Do not inspect the filesystem beyond the packet content.\n");
    text.push_str(
        "- Use only the source excerpts, target excerpts, and architecture notes in the packet.\n",
    );
    text.push_str("- Cite source facts before code using `facts/<table>.jsonl:<key>` or `evidence.db:<table>:<primary-key>`.\n");
    text.push_str("- Every behavior claim must have a source fact citation.\n");
    text.push_str("- Return `Source Evidence`, one proposed unified diff, then a short `Assumptions` section.\n");
    text.push_str("- If the packet is insufficient, return the smallest useful skeleton and name the missing excerpts.\n\n");
    text.push_str("## Patch Rules\n\n");
    text.push_str("- Existing files must be patched as existing files, not `new file mode`.\n");
    text.push_str("- New files are allowed only when listed in the packet target files.\n");
    text.push_str("- Do not introduce dependencies.\n");
    text.push_str("- Keep changes narrow and behavior-preserving.\n");
    std::fs::write(path, text).with_context(|| format!("write {path}"))
}

fn write_source_fidelity_reviewer(path: &Utf8Path) -> Result<()> {
    let mut text = String::new();
    text.push_str("# Codex Source-Fidelity Reviewer\n\n");
    text.push_str("Review a translator draft against only the source excerpts and cited knowledge rows in the packet.\n\n");
    text.push_str("## Review Duties\n\n");
    text.push_str("- Reject drafts without `Source Evidence` citations.\n");
    text.push_str("- Check cited `facts/*.jsonl` or `evidence.db` rows actually support the claimed behavior.\n");
    text.push_str("- Reject behavior invented without source evidence.\n");
    text.push_str("- Check enum order, integer discriminants, names, and branch behavior.\n");
    text.push_str("- Check that omitted behavior is listed as an assumption or blocker.\n");
    text.push_str("- Return findings only; do not rewrite the patch.\n");
    std::fs::write(path, text).with_context(|| format!("write {path}"))
}

fn write_rust_reviewer(path: &Utf8Path) -> Result<()> {
    let mut text = String::new();
    text.push_str("# Codex Rust Reviewer\n\n");
    text.push_str("Review a translator draft for Rust correctness, maintainability, and likely compile issues without running commands.\n\n");
    text.push_str("## Review Duties\n\n");
    text.push_str("- Check module declarations against the allowed target files.\n");
    text.push_str("- Check trait derives required by the draft's own use sites.\n");
    text.push_str("- Prefer constants/slices over heap maps for ordered source name tables.\n");
    text.push_str("- Return findings only; do not rewrite the patch.\n");
    std::fs::write(path, text).with_context(|| format!("write {path}"))
}

fn write_apply_converge_agent(path: &Utf8Path) -> Result<()> {
    let mut text = String::new();
    text.push_str("# Codex Apply/Converge Agent\n\n");
    text.push_str(
        "This is the only role allowed to edit the shared worktree and run verification.\n\n",
    );
    text.push_str("## Duties\n\n");
    text.push_str("- Apply only drafts that pass source-fidelity and Rust review.\n");
    text.push_str("- Reject drafts whose `Source Evidence` citations cannot be found in `facts/*.jsonl` or `evidence.db`.\n");
    text.push_str("- Run the allowed verification command for the packet.\n");
    text.push_str("- Record pass/fail evidence in `packet_outcomes.jsonl`.\n");
    text.push_str("- Keep fixes scoped to the current packet unless a verified compile error requires a small adjacent edit.\n");
    std::fs::write(path, text).with_context(|| format!("write {path}"))
}

fn write_codex_review_checklist(path: &Utf8Path) -> Result<()> {
    let mut text = String::new();
    text.push_str("# Codex Draft Review Checklist\n\n");
    text.push_str("A controller or apply/converge agent must reject a translator draft when any item fails.\n\n");
    text.push_str("## Safety\n\n");
    text.push_str("- [ ] Draft does not claim it ran commands.\n");
    text.push_str("- [ ] Draft does not mention Cargo/git/build/test output.\n");
    text.push_str("- [ ] Draft touches only target files named by the packet.\n");
    text.push_str("- [ ] Existing files are not marked as new files.\n");
    text.push_str("- [ ] No new dependencies or package-manager instructions appear.\n\n");
    text.push_str("## Source Fidelity\n\n");
    text.push_str("- [ ] Draft has a `Source Evidence` section with fact-row citations.\n");
    text.push_str("- [ ] Each cited fact row exists in `facts/*.jsonl` or `evidence.db`.\n");
    text.push_str("- [ ] Behavior claims are supported by the cited facts.\n");
    text.push_str(
        "- [ ] Every public enum preserves source variant order and explicit discriminants.\n",
    );
    text.push_str("- [ ] Helper functions mirror source branch behavior visible in the packet.\n");
    text.push_str("- [ ] Missing behavior is listed as an assumption, not silently invented.\n");
    text.push_str("- [ ] Names are traceable to source names or target architecture docs.\n\n");
    text.push_str("## Rust Fit\n\n");
    text.push_str("- [ ] Types derive traits required by their own use sites.\n");
    text.push_str("- [ ] Constants/slices are preferred over heap maps for ordered name tables.\n");
    text.push_str("- [ ] The patch is small enough for one apply/converge verification cycle.\n");
    std::fs::write(path, text).with_context(|| format!("write {path}"))
}

fn write_codex_runbook(path: &Utf8Path, profile: &PacketProfile) -> Result<()> {
    let mut text = String::new();
    text.push_str("# Codex Porting Runbook\n\n");
    text.push_str("Use Codex roles to translate, review, apply, and converge one bounded packet at a time.\n\n");
    text.push_str("## Flow\n\n");
    text.push_str("1. Controller selects one small `units/*/TASK.md` packet.\n");
    text.push_str("2. Translator drafts a patch using `agents/01-translator.md`.\n");
    text.push_str("3. Source-fidelity reviewer checks behavior against cited source fact rows.\n");
    text.push_str("4. Rust reviewer checks likely compile/design problems.\n");
    text.push_str("5. Apply/converge applies only accepted patches and runs verification.\n");
    text.push_str("6. Record accepted/rejected outcomes in `packet_outcomes.jsonl`.\n\n");
    text.push_str("## Default Profile\n\n");
    text.push_str(&format!(
        "- Max prompt bytes: `{}`\n",
        profile.max_prompt_bytes
    ));
    text.push_str(&format!(
        "- Require review before apply: `{}`\n",
        profile.require_review_before_apply
    ));
    text.push_str(&format!(
        "- Allow verification in worker: `{}`\n",
        profile.allow_verification
    ));
    text.push_str("\n## Token Discipline\n\n");
    text.push_str("- Use synthesis docs as an index, not as full prompt context.\n");
    text.push_str("- Include only the source excerpts, target excerpts, and fact rows required for the current packet.\n");
    text.push_str(
        "- Prefer `evidence.db` queries to broad source scans when selecting fact rows.\n",
    );
    text.push_str("- Prefer one narrow packet over a broad architectural translation.\n");
    std::fs::write(path, text).with_context(|| format!("write {path}"))
}

fn copy_evidence_queries(source: &Utf8Path, target_root: &Utf8Path) -> Result<()> {
    let source_queries = source.join(".c2rust-port/knowledge/EVIDENCE_QUERIES.md");
    if source_queries.exists() {
        std::fs::copy(&source_queries, target_root.join("EVIDENCE_QUERIES.md"))
            .with_context(|| format!("copy {source_queries}"))?;
    }
    Ok(())
}

fn validate_seed_citations(
    source: &Utf8Path,
    citations: &[String],
) -> Result<CitationValidationReport> {
    let rows = citations
        .iter()
        .map(|citation| validate_seed_citation(source, citation))
        .collect::<Result<Vec<_>>>()?;
    let status = if rows.is_empty() {
        "no_seed_citations"
    } else if rows.iter().all(|row| row.status == "ok") {
        "ok"
    } else {
        "failed"
    };
    Ok(CitationValidationReport {
        status: status.to_string(),
        rows,
    })
}

fn validate_seed_citation(source: &Utf8Path, citation: &str) -> Result<CitationValidationRow> {
    if let Some((table, key)) = parse_fact_citation(citation) {
        let rows = read_fact_rows(source, table)?;
        let resolved = rows.iter().any(|row| {
            row.get("key")
                .and_then(|value| value.as_str())
                .is_some_and(|value| value == key)
        });
        return Ok(CitationValidationRow {
            citation: citation.to_string(),
            status: if resolved { "ok" } else { "missing" }.to_string(),
            detail: if resolved {
                format!("resolved in facts/{table}.jsonl")
            } else {
                format!("missing key `{key}` in facts/{table}.jsonl")
            },
        });
    }
    if let Some((table, key)) = parse_evidence_db_citation(citation) {
        let resolved = evidence_db_fact_exists(source, table, key)?;
        return Ok(CitationValidationRow {
            citation: citation.to_string(),
            status: if resolved { "ok" } else { "missing" }.to_string(),
            detail: if resolved {
                format!("resolved in evidence.db facts table `{table}`")
            } else {
                format!("missing key `{key}` in evidence.db table `{table}`")
            },
        });
    }
    Ok(CitationValidationRow {
        citation: citation.to_string(),
        status: "unsupported".to_string(),
        detail: "expected `facts/<table>.jsonl:<key>` or `evidence.db:<table>:<primary-key>`"
            .to_string(),
    })
}

fn parse_fact_citation(citation: &str) -> Option<(&str, &str)> {
    let rest = citation.strip_prefix("facts/")?;
    let (table, key) = rest.split_once(".jsonl:")?;
    (!table.is_empty() && !key.is_empty()).then_some((table, key))
}

fn parse_evidence_db_citation(citation: &str) -> Option<(&str, &str)> {
    let rest = citation.strip_prefix("evidence.db:")?;
    let (table, key) = rest.split_once(':')?;
    (!table.is_empty() && !key.is_empty()).then_some((table, key))
}

fn evidence_db_fact_exists(source: &Utf8Path, table: &str, key: &str) -> Result<bool> {
    let path = source.join(".c2rust-port/knowledge/evidence.db");
    if !path.exists() {
        return Ok(false);
    }
    let conn = Connection::open(path.as_std_path()).with_context(|| format!("open {path}"))?;
    let count: i64 = conn
        .query_row(
            "SELECT count(*) FROM facts WHERE table_name = ?1 AND key = ?2",
            params![table, key],
            |row| row.get(0),
        )
        .with_context(|| format!("query citation {table}:{key}"))?;
    Ok(count > 0)
}

fn write_citation_validation(root: &Utf8Path, report: &CitationValidationReport) -> Result<()> {
    std::fs::write(
        root.join("CITATION_VALIDATION.json"),
        serde_json::to_string_pretty(report)?,
    )
    .with_context(|| format!("write {}", root.join("CITATION_VALIDATION.json")))?;

    let mut text = String::new();
    text.push_str("# Citation Validation\n\n");
    text.push_str(&format!("- Status: `{}`\n", report.status));
    text.push_str(&format!("- Checked citations: `{}`\n\n", report.rows.len()));
    if report.rows.is_empty() {
        text.push_str("No seed citations were generated for this packet.\n");
    } else {
        text.push_str("| Citation | Status | Detail |\n");
        text.push_str("| --- | --- | --- |\n");
        for row in &report.rows {
            text.push_str(&format!(
                "| `{}` | `{}` | {} |\n",
                markdown_table_cell(&row.citation),
                row.status,
                markdown_table_cell(&row.detail)
            ));
        }
    }
    std::fs::write(root.join("CITATION_VALIDATION.md"), text)
        .with_context(|| format!("write {}", root.join("CITATION_VALIDATION.md")))?;
    Ok(())
}

fn ensure_citation_validation_passed(report: &CitationValidationReport) -> Result<()> {
    if report.status == "failed" {
        let missing = report
            .rows
            .iter()
            .filter(|row| row.status != "ok")
            .map(|row| format!("{} ({})", row.citation, row.detail))
            .collect::<Vec<_>>()
            .join("; ");
        anyhow::bail!("generated packet has unresolved seed citations: {missing}");
    }
    Ok(())
}

fn markdown_table_cell(input: &str) -> String {
    input.replace('|', "\\|").replace('\n', "<br>")
}

fn select_packet_slice(source: &Utf8Path, limit: usize) -> Result<PacketSlice> {
    let mut slice = PacketSlice {
        feature: "indexing".to_string(),
        files: Vec::new(),
        citations: Vec::new(),
        blockers: source_map_blockers(source)?,
    };
    let mut files = BTreeSet::<Utf8PathBuf>::new();
    let mut citations = BTreeSet::<String>::new();
    for table in [
        "feature_tags",
        "symbols",
        "call_edges",
        "dataflow_edges",
        "equivalence_edges",
        "equivalence_diffs",
    ] {
        for row in read_fact_rows(source, table)? {
            if !row_mentions_feature(&row, "indexing") {
                continue;
            }
            if let Some(citation) = fact_citation(table, &row) {
                citations.insert(citation);
            }
            for file in source_files_from_fact(source, &row) {
                files.insert(file);
            }
        }
    }
    if files.is_empty() {
        slice.feature = "source-map".to_string();
        files.extend(first_source_files(source, limit)?);
    }
    slice.files = files.into_iter().take(limit).collect();
    slice.citations = citations.into_iter().take(12).collect();
    Ok(slice)
}

fn read_fact_rows(source: &Utf8Path, table: &str) -> Result<Vec<serde_json::Value>> {
    let path = source.join(format!(".c2rust-port/knowledge/facts/{table}.jsonl"));
    if !path.exists() {
        return Ok(Vec::new());
    }
    let text = std::fs::read_to_string(&path).with_context(|| format!("read {path}"))?;
    let mut rows = Vec::new();
    for (index, line) in text.lines().enumerate() {
        if line.trim().is_empty() {
            continue;
        }
        rows.push(
            serde_json::from_str(line)
                .with_context(|| format!("parse {path} line {}", index + 1))?,
        );
    }
    Ok(rows)
}

fn source_map_blockers(source: &Utf8Path) -> Result<Vec<String>> {
    let mut blockers = Vec::new();
    for row in read_fact_rows(source, "capabilities")? {
        let name = row
            .get("name")
            .and_then(|value| value.as_str())
            .unwrap_or("");
        let status = row
            .get("status")
            .and_then(|value| value.as_str())
            .unwrap_or("");
        if !matches!(name, "codeql" | "doxygen") || status != "ran_failed" {
            continue;
        }
        let blocker_text = row
            .get("blockers")
            .and_then(|value| value.as_array())
            .into_iter()
            .flatten()
            .filter_map(|value| value.as_str())
            .collect::<Vec<_>>()
            .join("; ");
        blockers.push(if blocker_text.is_empty() {
            format!("`{name}` failed; inspect capability and tool-run facts.")
        } else {
            format!("`{name}` failed: {blocker_text}")
        });
    }
    Ok(blockers)
}

fn row_mentions_feature(row: &serde_json::Value, feature: &str) -> bool {
    if row
        .get("feature")
        .and_then(|value| value.as_str())
        .is_some_and(|value| value == feature)
    {
        return true;
    }
    let text = serde_json::to_string(row)
        .unwrap_or_default()
        .to_ascii_lowercase();
    match feature {
        "indexing" => [
            "index",
            "idx",
            "bwt",
            "ebwt",
            "fm_index",
            "fm-index",
            "suffix",
            "sais",
            "blockwise",
        ]
        .iter()
        .any(|needle| text.contains(needle)),
        _ => text.contains(feature),
    }
}

fn fact_citation(table: &str, row: &serde_json::Value) -> Option<String> {
    row.get("key")
        .and_then(|value| value.as_str())
        .map(|key| format!("facts/{table}.jsonl:{key}"))
}

fn source_files_from_fact(source: &Utf8Path, row: &serde_json::Value) -> Vec<Utf8PathBuf> {
    let mut files = Vec::new();
    for key in [
        "path",
        "cpp_path",
        "source",
        "from",
        "caller",
        "entity",
        "cpp_entity",
    ] {
        if let Some(value) = row.get(key).and_then(|value| value.as_str()) {
            if let Some(path) = normalize_source_file_path(source, value) {
                files.push(path);
            }
        }
    }
    files
}

fn normalize_source_file_path(source: &Utf8Path, value: &str) -> Option<Utf8PathBuf> {
    let path = Utf8Path::new(value);
    let relative = if path.is_absolute() {
        path.strip_prefix(source).ok()?.to_path_buf()
    } else {
        path.to_path_buf()
    };
    is_c_or_cpp_file(&relative).then_some(relative)
}

fn first_source_files(source: &Utf8Path, limit: usize) -> Result<Vec<Utf8PathBuf>> {
    let mut files = Vec::new();
    for entry in WalkDir::new(source).into_iter().filter_map(Result::ok) {
        if !entry.file_type().is_file() {
            continue;
        }
        let path = Utf8PathBuf::from_path_buf(entry.path().to_path_buf())
            .map_err(|p| anyhow::anyhow!("non-utf8 path: {}", p.display()))?;
        if is_c_or_cpp_file(&path) {
            files.push(path.strip_prefix(source).unwrap_or(&path).to_path_buf());
        }
        if files.len() >= limit {
            break;
        }
    }
    Ok(files)
}

fn is_c_or_cpp_file(path: &Utf8Path) -> bool {
    matches!(
        path.extension(),
        Some("c" | "cc" | "cpp" | "cxx" | "C" | "h" | "hh" | "hpp" | "hxx")
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn packet_profile_round_trips() {
        let dir = camino::Utf8PathBuf::from_path_buf(
            std::env::temp_dir().join(format!("c2rust-port-profile-test-{}", std::process::id())),
        )
        .unwrap();
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("profile.toml");
        let profile = PacketProfile::default();
        profile.write_to(&path).unwrap();
        assert_eq!(PacketProfile::read_from(&path).unwrap(), profile);
        let _ = std::fs::remove_file(path);
        let _ = std::fs::remove_dir(dir);
    }

    #[test]
    fn source_map_blockers_include_failed_deep_tools() {
        let dir = camino::Utf8PathBuf::from_path_buf(std::env::temp_dir())
            .unwrap()
            .join(format!("c2rust-port-blocker-test-{}", std::process::id()));
        let facts = dir.join(".c2rust-port/knowledge/facts");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&facts).unwrap();
        std::fs::write(
            facts.join("capabilities.jsonl"),
            "{\"fact_type\":\"capability\",\"key\":\"doxygen\",\"name\":\"doxygen\",\"status\":\"ran_failed\",\"blockers\":[\"doxygen failed with exit 1\"],\"provenance\":[\"tool-audit\"]}\n",
        )
        .unwrap();
        let blockers = source_map_blockers(&dir).unwrap();
        assert_eq!(blockers.len(), 1);
        assert!(blockers[0].contains("doxygen"));
        assert!(blockers[0].contains("exit 1"));
        let _ = std::fs::remove_dir_all(dir);
    }

    #[test]
    fn citation_validator_resolves_jsonl_and_sqlite_rows() {
        let dir = camino::Utf8PathBuf::from_path_buf(std::env::temp_dir())
            .unwrap()
            .join(format!("c2rust-port-citation-test-{}", std::process::id()));
        let facts = dir.join(".c2rust-port/knowledge/facts");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&facts).unwrap();
        std::fs::write(
            facts.join("symbols.jsonl"),
            "{\"fact_type\":\"symbol\",\"key\":\"source:index.cpp:build_index\",\"name\":\"build_index\",\"provenance\":[\"test\"]}\n",
        )
        .unwrap();
        let db_path = dir.join(".c2rust-port/knowledge/evidence.db");
        let conn = Connection::open(db_path.as_std_path()).unwrap();
        conn.execute_batch(
            "CREATE TABLE facts (
                table_name TEXT NOT NULL,
                key TEXT NOT NULL,
                fact_type TEXT,
                json TEXT NOT NULL,
                provenance_json TEXT NOT NULL,
                PRIMARY KEY (table_name, key)
            );",
        )
        .unwrap();
        conn.execute(
            "INSERT INTO facts(table_name, key, fact_type, json, provenance_json)
             VALUES (?1, ?2, ?3, ?4, ?5)",
            params![
                "symbols",
                "source:index.cpp:build_index",
                "symbol",
                "{}",
                "[]"
            ],
        )
        .unwrap();

        let report = validate_seed_citations(
            &dir,
            &[
                "facts/symbols.jsonl:source:index.cpp:build_index".to_string(),
                "evidence.db:symbols:source:index.cpp:build_index".to_string(),
            ],
        )
        .unwrap();
        assert_eq!(report.status, "ok");
        assert_eq!(report.rows.len(), 2);
        let _ = std::fs::remove_dir_all(dir);
    }

    #[test]
    fn citation_validator_reports_missing_rows() {
        let dir = camino::Utf8PathBuf::from_path_buf(std::env::temp_dir())
            .unwrap()
            .join(format!(
                "c2rust-port-citation-missing-test-{}",
                std::process::id()
            ));
        let facts = dir.join(".c2rust-port/knowledge/facts");
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&facts).unwrap();
        std::fs::write(facts.join("symbols.jsonl"), "").unwrap();
        let report =
            validate_seed_citations(&dir, &["facts/symbols.jsonl:missing".to_string()]).unwrap();
        assert_eq!(report.status, "failed");
        assert_eq!(report.rows[0].status, "missing");
        assert!(ensure_citation_validation_passed(&report).is_err());
        let _ = std::fs::remove_dir_all(dir);
    }
}
